### ISSUE TITLE
Paper still todo

### ISSUE THREAD

**Issue by tomclose** [magmo/nitro-paper#1]
- [ ] Existing work section
- [ ] Acknowledgements
- [ ] Python(?) implementation of turbo adjudicator
- [ ] Python(?) implementation of nitro adjudicator
- [ ] Proofs of open/closing etc. in appendix
- [ ] Mention the virtual channel on turbo construction
- [ ] References
- [ ] Overview of ForceMove in appendix
